name: Database Validation

on:
  pull_request:
    paths:
      - 'supabase/schemas/**'
      - 'supabase/seeds/**'
      - 'supabase/tests/**'
      - 'supabase/migrations/**'
      - 'scripts/db.migrate.seed.test.sh'
  push:
    branches:
      - main
    paths:
      - 'supabase/schemas/**'
      - 'supabase/seeds/**'
      - 'supabase/tests/**'
      - 'supabase/migrations/**'
      - 'scripts/db.migrate.seed.test.sh'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Start local Supabase instance
        run: |
          supabase start

      - name: Get database connection string
        run: |
          echo "SUPABASE_DB_URL=postgresql://postgres:postgres@127.0.0.1:54322/postgres" >> $GITHUB_ENV

      - name: Run migration, seed, and validation script
        env:
          SUPABASE_DB_URL: ${{ env.SUPABASE_DB_URL }}
        run: |
          bash scripts/db.migrate.seed.test.sh

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: validation-logs
          path: /tmp/*.log
          retention-days: 7

      - name: Stop Supabase
        if: always()
        run: |
          supabase stop
